### ISSUE TITLE
Add color palettes

### ISSUE THREAD

**Issue by dshubhadeep** [dshubhadeep/Color-System#1]
The site contains only 2 palettes at the moment - 
* Atlassian
* Tailwind

More palettes need to be added to the `src/data` folder

The palette file should be in following json format
```json
{
    "name": "Name of design system/framework ",
    "url": "Url to the design system's color palette",
    "palettes": [
        {
            "color": "color",
            "swatch": [
                {
                    "hex": "hex value of color",
                    "rgb": "rgb value of color"
                }
            ]
        }
    ]
}
``` 
For reference, see [atlassian.json](https://github.com/dshubhadeep/Color-System/blob/master/src/data/atlassian.json)

The file name should be in **lowercase** and same as the `name` field in the json file.
If the name has **more** than 1 word, seperate using `_`,  e.g. a_b.json, 
the `name` field should seperated by space, e.g. `name : "a b"`

You can run the following scripts to ensure that the file is properly formatted.

```bash
# This script transforms the file by adding a rgb field to the 
# swatch object if there is a hex value present and vice versa.
# and also ensures that swatches and palettes are sorted properly

npm run transform:data # for all files
npm run transform:data ./src/data/<filename>.json # for a single file
```

```bash
# This script validates the json files present in src/data

npm run validate:data # for all files
npm run validate:data ./src/data/<filename>.json # for a single file
```

**Comment by poojakp94** [comment]
@dshubhadeep I would like to work on this.

**Comment by dshubhadeep** [comment]
@poojakp94  Sure, you can use this for reference - [design systems](https://github.com/alexpate/awesome-design-systems). 

Do comment on the design system you are working on so there are no duplications.

**Comment by Glassig** [comment]
Hi, I would like to add Stackoverflow (according to: [stacks colors](https://stackoverflow.design/product/base/colors) ).

**Comment by smithshelke** [comment]
hey i want to create a pull request for hacktoberfest

**Comment by smithshelke** [comment]
lol
