### ISSUE TITLE
Add scroll to top button

### ISSUE THREAD

**Issue by dshubhadeep** [dshubhadeep/Color-System#3]
Add scroll to top button in the [color system page](https://github.com/dshubhadeep/Color-System/blob/master/src/templates/color-system.jsx).

**Comment by rajdama** [comment]
I can do it.

**Comment by SamikshaSankar** [comment]
Please assign me

**Comment by dshubhadeep** [comment]
Assigned to @rajdama 
Sorry @SamikshaSankar, I'm planning to create 1 more issue so you can work on that, if interested.

**Comment by dshubhadeep** [comment]
@rajdama are you working on this ?

**Comment by rajdama** [comment]
@dshubhadeep  After cloning the repo and doing npm install and writing  npm run dev it shows error.

**Comment by dshubhadeep** [comment]
@rajdama what is the error ? Could you provide screenshot ?

**Comment by dshubhadeep** [comment]
Can you try `node ./node_modules/.bin/gatsby develop -p 3000` or try installing gatsby globally using `npm i -g gatsby@2.24.47` ?

**Comment by rajdama** [comment]
ok

**Comment by rajdama** [comment]
Still not working.

**Comment by rajdama** [comment]
![scroll](https://user-images.githubusercontent.com/75741866/136691356-1d446ebc-ef93-4dee-a2d4-a48369b51598.png)
Scroll to top added
